In [16]:
import pandas as pd
import numpy as np

df=pd.read_csv("Data.csv")
print('Original Data : \n',df)

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imp.fit(x[:,1:3])
x[:,1:3]=imp.transform(x[:,1:3])
print('transform Data : \n',x)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
T = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
P = np.array(T.fit_transform(x))
print('For Non-Numerical-Country- data For X Part :\n',P)

from sklearn.preprocessing import LabelEncoder
L = LabelEncoder()
y = L.fit_transform(y)
print('For Y Part : \n',y)


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print("X Part of Train :",x_train)
print("Y Part of Train :",y_train)

# Normalization Or Min_Max Scale
# X_min = (X - X_min) / (X_min - X_max)

from sklearn.preprocessing import MinMaxScaler
nm = MinMaxScaler()
x_train[:, 3:] = nm.fit_transform(x_train[:, 3:])
x_test[:, 3:] = nm.transform(x_test[:, 3:])

print(x_train[:, 3:])

Original Data : 
    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
transform Data : 
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
For Non-Numerical-Country- data For X Part :
 [[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]


ValueError: Found array with 0 feature(s) (shape=(8, 0)) while a minimum of 1 is required by MinMaxScaler.